# Generated by Django 5.0.1 on 2024-02-04 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedetails',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 3, 23, 50, 30, 494741)),
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='mfg_date',
            field=models.DateField(default=datetime.date(2024, 2, 4)),
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
