# Generated by Django 5.0.1 on 2024-02-04 18:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisite', '0002_medicinedetails_exp_date_medicinedetails_mfg_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 0, 12, 44, 162398)),
        ),
        migrations.AlterField(
            model_name='medicinedetails',
            name='mfg_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
