# Generated by Django 5.0.1 on 2024-02-06 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisite', '0003_alter_medicinedetails_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 14, 8, 31, 661933)),
        ),
    ]
